### PR TITLE
curl_easy_escape: byte length (sizeof) instead of character length.

### PR DESCRIPTION
**Pull request by phanalpha**

### CODE REVIEW

**Comment by IainNZ** [comment]
Seems to have caused a segfault on Julia 0.4... any ideas?

**Comment by phanalpha** [comment]
I've tested a new nightly build 0.4 (`julia-0.4.0-93e672d866-linux64.tar.gz`), on `Linux deidre 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux` with `libcurl4-gnutls-dev`. For ascii string, sizeof produce the same result as length (so it should be safe); and for utf8 string, it's the size of string.data which should be safe too (at least no segfault). In both cases, it works. So can you confirm it's sizeof modification crash Julia, or do i miss anything?

```
julia> HTTPC.post("http://httpbin.org/post", { "hello" => "world" })
"{\n  \"args\": {}, \n  \"data\": \"\", \n  \"files\": {}, \n  \"form\": {\n    \"hello\": \"world\"\n  }, \n  \"headers\": {\n    \"Accept\": \"*/*\", \n    \"Content-Length\": \"11\", \n    \"Content-Type\": \"application/x-www-form-urlencoded\", \n    \"Host\": \"httpbin.org\"\n  }, \n  \"json\": null, \n  \"origin\": \"111.201.1.40\", \n  \"url\": \"http://httpbin.org/post\"\n}\n"

julia> HTTPC.post("http://httpbin.org/post", { "你好" => "世界" })
"{\n  \"args\": {}, \n  \"data\": \"\", \n  \"files\": {}, \n  \"form\": {\n    \"\\u4f60\\u597d\": \"\\u4e16\\u754c\"\n  }, \n  \"headers\": {\n    \"Accept\": \"*/*\", \n    \"Content-Length\": \"37\", \n    \"Content-Type\": \"application/x-www-form-urlencoded\", \n    \"Host\": \"httpbin.org\"\n  }, \n  \"json\": null, \n  \"origin\": \"111.201.1.40\", \n  \"url\": \"http://httpbin.org/post\"\n}\n"
```

**Comment by IainNZ** [comment]
I'm really not sure, I was just looking at the Travis logs:
```
INFO: Testing HTTPClient
signal (11): Segmentation fault
curl_easy_cleanup at /home/travis/.julia/v0.4/LibCURL/src/lC_common_h.jl:4
=============================[ ERROR: HTTPClient ]==============================
failed process: Process(`/home/travis/julia/bin/julia --check-bounds=yes --code-coverage=user --inline=no --color=no /home/travis/.julia/v0.4/HTTPClient/test/runtests.jl`, ProcessSignaled(11)) [0]
================================================================================
```
Certainly sizeof makes more sense to me - maybe the pacakge is already broken on 0.4 anyway, and its not the fault of this change?
@amitmurthy wrote this package, I'll let him comment

**Comment by amitmurthy** [comment]
The Travis seg fault is unrelated. It is present in the current master too that I am unable to get a handle on. 0.4 tests pass locally but segfaults on Travis.

**Pull request merged**
